export const items = [
  {
    id: 1,
    name: "Grain-Free Turkey Feast",
    about: "Grain-free dry food with turkey.",
    description: "High-quality grain-free turkey recipe for optimal digestion.",
    ingredients: ["Turkey", "Peas", "Sweet Potatoes", "Vitamins", "Minerals"],
    price: 30.99,
    quantity: ["4 lb", "8 lb"],
    img: "https://m.media-amazon.com/images/I/61wjplwWsXL.__AC_SX300_SY300_QL70_FMwebp_.jpg",
    category: "Dry Food",
    brand: "Chewy",
  },
  {
    id: 2,
    name: "Raw Beef Bites",
    about: "Frozen raw beef with added nutrients.",
    description: "Nutrient-packed frozen raw beef bites to promote healthy muscle growth.",
    ingredients: ["Beef", "Liver", "Bone Meal", "Natural Flavors"],
    price: 39.99,
    quantity: ["3 lb", "6 lb"],
    img: "https://m.media-amazon.com/images/I/71ZPFjth5zL._AC_UL640_FMwebp_QL65_.jpg",
    category: "Fresh Food & Toppers",
    brand: "Addiction",
  },
  {
    id: 3,
    name: "Dehydrated Lamb Meal",
    about: "Dehydrated lamb, needs rehydration.",
    description: "Dehydrated lamb meal with added nutrients for a balanced diet.",
    ingredients: ["Lamb", "Carrots", "Celery", "Spinach", "Vitamins"],
    price: 29.99,
    quantity: ["2 lb", "5 lb"],
    img: "https://m.media-amazon.com/images/I/61DwrCterZL._AC_UL640_FMwebp_QL65_.jpg",
    category: "Dry Food",
    brand: "Annamaet",
  },
  {
    id: 4,
    name: "Senior Wellness Formula",
    about: "Dry food for senior pets.",
    description: "Special formula for senior pets to support joint health and vitality.",
    ingredients: ["Chicken", "Rice", "Omega-3", "Vitamins", "Minerals"],
    price: 24.99,
    quantity: ["5 lb", "10 lb"],
    img: "https://m.media-amazon.com/images/I/71KZEymfxdL._AC_UL640_FMwebp_QL65_.jpg",
    category: "Veterinary Diets",
    brand: "ACANA",
  },
  {
    id: 5,
    name: "Puppy Growth Mix",
    about: "Protein-rich food for puppies.",
    description: "High-protein formula designed for growing puppies.",
    ingredients: ["Chicken", "Brown Rice", "Fish Oil", "DHA", "Vitamins"],
    price: 27.99,
    quantity: ["6 lb", "12 lb"],
    img: "https://m.media-amazon.com/images/I/71OFWlY5e8L._AC_UL640_FMwebp_QL65_.jpg",
    category: "Puppy Food",
    brand: "American Journey",
  },
  {
    id: 6,
    name: "Limited Ingredient Duck & Sweet Potato",
    about: "Duck and sweet potato formula.",
    description: "Perfect for sensitive stomachs with limited ingredients.",
    ingredients: ["Duck", "Sweet Potato", "Peas", "Flaxseed", "Vitamins"],
    price: 34.99,
    quantity: ["4 lb", "8 lb"],
    img: "https://m.media-amazon.com/images/I/718uKj5wxQL._AC_UL640_FMwebp_QL65_.jpg",
    category: "Dry Food",
    brand: "American Natural Premium",
  },
  {
    id: 7,
    name: "Salmon & Pea Recipe",
    about: "High-protein salmon and peas.",
    description: "Protein-rich salmon formula ideal for active pets.",
    ingredients: ["Salmon", "Peas", "Potatoes", "Carrots", "Vitamins"],
    price: 28.99,
    quantity: ["5 lb", "10 lb"],
    img: "https://m.media-amazon.com/images/I/51pEKV4sfXL._AC_UL640_FMwebp_QL65_.jpg",
    category: "Dry Food",
    brand: "Artemis",
  },
  {
    id: 8,
    name: "Chicken & Brown Rice Stew",
    about: "Wet food with chicken and rice.",
    description: "Delicious wet food with tender chicken and wholesome rice.",
    ingredients: ["Chicken", "Brown Rice", "Vegetables", "Vitamins"],
    price: 18.99,
    quantity: ["12 cans (3.5 oz each)", "24 cans (3.5 oz each)"],
    img: "https://m.media-amazon.com/images/I/718HoxLmQTL._AC_UL640_FMwebp_QL65_.jpg",
    category: "Wet Food",
    brand: "Annamaet",
  },
  {
    id: 9,
    name: "Organic Chicken & Quinoa",
    about: "Organic food with chicken and quinoa.",
    description: "A premium blend of organic chicken and quinoa for optimal health.",
    ingredients: ["Organic Chicken", "Quinoa", "Sweet Potatoes", "Spinach"],
    price: 32.99,
    quantity: ["5 lb", "10 lb"],
    img: "https://m.media-amazon.com/images/I/61ePMgx0n4L._AC_UL640_FMwebp_QL65_.jpg",
    category: "Dry Food",
    brand: "ACANA",
  },
  {
    id: 10,
    name: "Weight Management Blend",
    about: "Low-calorie food for weight control.",
    description: "Low-calorie blend to help pets maintain a healthy weight.",
    ingredients: ["Chicken", "Barley", "Peas", "Vitamins", "Minerals"],
    price: 29.99,
    quantity: ["6 lb", "12 lb"],
    img: "https://image.chewy.com/is/image/catalog/259516_MAIN._AC_SS348_V1712635267_.jpg",
    category: "Veterinary Diets",
    brand: "Chewy",
  },
  {
    id: 11,
    name: "Hairball Control Formula",
    about: "Food to help control hairballs.",
    description: "Specially formulated to reduce hairballs in cats.",
    ingredients: ["Chicken", "Rice", "Fiber", "Omega-3"],
    price: 26.99,
    quantity: ["5 lb", "10 lb"],
    img: "https://image.chewy.com/is/image/catalog/259516_MAIN._AC_SS348_V1712635267_.jpg",
    category: "Shop by Health Condition",
    brand: "Artemis",
  },
  {
    id: 1,
    name: "Grain-Free Turkey Feast",
    about: "Grain-free dry food with turkey.",
    description: "High-quality grain-free turkey recipe for optimal digestion.",
    ingredients: ["Turkey", "Peas", "Sweet Potatoes", "Vitamins", "Minerals"],
    price: 30.99,
    quantity: ["4 lb", "8 lb"],
    img: "https://m.media-amazon.com/images/I/61wjplwWsXL.__AC_SX300_SY300_QL70_FMwebp_.jpg",
    category: "Dry Food",
    brand: "Chewy",
  },
  {
    id: 2,
    name: "Raw Beef Bites",
    about: "Frozen raw beef with added nutrients.",
    description: "Nutrient-packed frozen raw beef bites to promote healthy muscle growth.",
    ingredients: ["Beef", "Liver", "Bone Meal", "Natural Flavors"],
    price: 39.99,
    quantity: ["3 lb", "6 lb"],
    img: "https://m.media-amazon.com/images/I/71ZPFjth5zL._AC_UL640_FMwebp_QL65_.jpg",
    category: "Fresh Food & Toppers",
    brand: "Addiction",
  },
  {
    id: 3,
    name: "Dehydrated Lamb Meal",
    about: "Dehydrated lamb, needs rehydration.",
    description: "Dehydrated lamb meal with added nutrients for a balanced diet.",
    ingredients: ["Lamb", "Carrots", "Celery", "Spinach", "Vitamins"],
    price: 29.99,
    quantity: ["2 lb", "5 lb"],
    img: "https://m.media-amazon.com/images/I/61DwrCterZL._AC_UL640_FMwebp_QL65_.jpg",
    category: "Dry Food",
    brand: "Annamaet",
  },
  {
    id: 4,
    name: "Senior Wellness Formula",
    about: "Dry food for senior pets.",
    description: "Special formula for senior pets to support joint health and vitality.",
    ingredients: ["Chicken", "Rice", "Omega-3", "Vitamins", "Minerals"],
    price: 24.99,
    quantity: ["5 lb", "10 lb"],
    img: "https://m.media-amazon.com/images/I/71KZEymfxdL._AC_UL640_FMwebp_QL65_.jpg",
    category: "Veterinary Diets",
    brand: "ACANA",
  },
  {
    id: 5,
    name: "Puppy Growth Mix",
    about: "Protein-rich food for puppies.",
    description: "High-protein formula designed for growing puppies.",
    ingredients: ["Chicken", "Brown Rice", "Fish Oil", "DHA", "Vitamins"],
    price: 27.99,
    quantity: ["6 lb", "12 lb"],
    img: "https://m.media-amazon.com/images/I/71OFWlY5e8L._AC_UL640_FMwebp_QL65_.jpg",
    category: "Puppy Food",
    brand: "American Journey",
  },
  {
    id: 6,
    name: "Limited Ingredient Duck & Sweet Potato",
    about: "Duck and sweet potato formula.",
    description: "Perfect for sensitive stomachs with limited ingredients.",
    ingredients: ["Duck", "Sweet Potato", "Peas", "Flaxseed", "Vitamins"],
    price: 34.99,
    quantity: ["4 lb", "8 lb"],
    img: "https://m.media-amazon.com/images/I/718uKj5wxQL._AC_UL640_FMwebp_QL65_.jpg",
    category: "Dry Food",
    brand: "American Natural Premium",
  },
  {
    id: 7,
    name: "Salmon & Pea Recipe",
    about: "High-protein salmon and peas.",
    description: "Protein-rich salmon formula ideal for active pets.",
    ingredients: ["Salmon", "Peas", "Potatoes", "Carrots", "Vitamins"],
    price: 28.99,
    quantity: ["5 lb", "10 lb"],
    img: "https://m.media-amazon.com/images/I/51pEKV4sfXL._AC_UL640_FMwebp_QL65_.jpg",
    category: "Dry Food",
    brand: "Artemis",
  },
  {
    id: 8,
    name: "Chicken & Brown Rice Stew",
    about: "Wet food with chicken and rice.",
    description: "Delicious wet food with tender chicken and wholesome rice.",
    ingredients: ["Chicken", "Brown Rice", "Vegetables", "Vitamins"],
    price: 18.99,
    quantity: ["12 cans (3.5 oz each)", "24 cans (3.5 oz each)"],
    img: "https://m.media-amazon.com/images/I/718HoxLmQTL._AC_UL640_FMwebp_QL65_.jpg",
    category: "Wet Food",
    brand: "Annamaet",
  },
  {
    id: 9,
    name: "Organic Chicken & Quinoa",
    about: "Organic food with chicken and quinoa.",
    description: "A premium blend of organic chicken and quinoa for optimal health.",
    ingredients: ["Organic Chicken", "Quinoa", "Sweet Potatoes", "Spinach"],
    price: 32.99,
    quantity: ["5 lb", "10 lb"],
    img: "https://m.media-amazon.com/images/I/61ePMgx0n4L._AC_UL640_FMwebp_QL65_.jpg",
    category: "Dry Food",
    brand: "ACANA",
  },
  {
    id: 10,
    name: "Weight Management Blend",
    about: "Low-calorie food for weight control.",
    description: "Low-calorie blend to help pets maintain a healthy weight.",
    ingredients: ["Chicken", "Barley", "Peas", "Vitamins", "Minerals"],
    price: 29.99,
    quantity: ["6 lb", "12 lb"],
    img: "https://image.chewy.com/is/image/catalog/259516_MAIN._AC_SS348_V1712635267_.jpg",
    category: "Veterinary Diets",
    brand: "Chewy",
  },
  {
    id: 11,
    name: "Hairball Control Formula",
    about: "Food to help control hairballs.",
    description: "Specially formulated to reduce hairballs in cats.",
    ingredients: ["Chicken", "Rice", "Fiber", "Omega-3"],
    price: 26.99,
    quantity: ["5 lb", "10 lb"],
    img: "https://image.chewy.com/is/image/catalog/259516_MAIN._AC_SS348_V1712635267_.jpg",
    category: "Shop by Health Condition",
    brand: "Artemis",
  },
  {
    id: 1,
    name: "Grain-Free Turkey Feast",
    about: "Grain-free dry food with turkey.",
    description: "High-quality grain-free turkey recipe for optimal digestion.",
    ingredients: ["Turkey", "Peas", "Sweet Potatoes", "Vitamins", "Minerals"],
    price: 30.99,
    quantity: ["4 lb", "8 lb"],
    img: "https://m.media-amazon.com/images/I/61wjplwWsXL.__AC_SX300_SY300_QL70_FMwebp_.jpg",
    category: "Dry Food",
    brand: "Chewy",
  },
  {
    id: 2,
    name: "Raw Beef Bites",
    about: "Frozen raw beef with added nutrients.",
    description: "Nutrient-packed frozen raw beef bites to promote healthy muscle growth.",
    ingredients: ["Beef", "Liver", "Bone Meal", "Natural Flavors"],
    price: 39.99,
    quantity: ["3 lb", "6 lb"],
    img: "https://m.media-amazon.com/images/I/71ZPFjth5zL._AC_UL640_FMwebp_QL65_.jpg",
    category: "Fresh Food & Toppers",
    brand: "Addiction",
  },
  {
    id: 3,
    name: "Dehydrated Lamb Meal",
    about: "Dehydrated lamb, needs rehydration.",
    description: "Dehydrated lamb meal with added nutrients for a balanced diet.",
    ingredients: ["Lamb", "Carrots", "Celery", "Spinach", "Vitamins"],
    price: 29.99,
    quantity: ["2 lb", "5 lb"],
    img: "https://m.media-amazon.com/images/I/61DwrCterZL._AC_UL640_FMwebp_QL65_.jpg",
    category: "Dry Food",
    brand: "Annamaet",
  },
  {
    id: 4,
    name: "Senior Wellness Formula",
    about: "Dry food for senior pets.",
    description: "Special formula for senior pets to support joint health and vitality.",
    ingredients: ["Chicken", "Rice", "Omega-3", "Vitamins", "Minerals"],
    price: 24.99,
    quantity: ["5 lb", "10 lb"],
    img: "https://m.media-amazon.com/images/I/71KZEymfxdL._AC_UL640_FMwebp_QL65_.jpg",
    category: "Veterinary Diets",
    brand: "ACANA",
  },
  {
    id: 5,
    name: "Puppy Growth Mix",
    about: "Protein-rich food for puppies.",
    description: "High-protein formula designed for growing puppies.",
    ingredients: ["Chicken", "Brown Rice", "Fish Oil", "DHA", "Vitamins"],
    price: 27.99,
    quantity: ["6 lb", "12 lb"],
    img: "https://m.media-amazon.com/images/I/71OFWlY5e8L._AC_UL640_FMwebp_QL65_.jpg",
    category: "Puppy Food",
    brand: "American Journey",
  },
  {
    id: 6,
    name: "Limited Ingredient Duck & Sweet Potato",
    about: "Duck and sweet potato formula.",
    description: "Perfect for sensitive stomachs with limited ingredients.",
    ingredients: ["Duck", "Sweet Potato", "Peas", "Flaxseed", "Vitamins"],
    price: 34.99,
    quantity: ["4 lb", "8 lb"],
    img: "https://m.media-amazon.com/images/I/718uKj5wxQL._AC_UL640_FMwebp_QL65_.jpg",
    category: "Dry Food",
    brand: "American Natural Premium",
  },
  {
    id: 7,
    name: "Salmon & Pea Recipe",
    about: "High-protein salmon and peas.",
    description: "Protein-rich salmon formula ideal for active pets.",
    ingredients: ["Salmon", "Peas", "Potatoes", "Carrots", "Vitamins"],
    price: 28.99,
    quantity: ["5 lb", "10 lb"],
    img: "https://m.media-amazon.com/images/I/51pEKV4sfXL._AC_UL640_FMwebp_QL65_.jpg",
    category: "Dry Food",
    brand: "Artemis",
  },
  {
    id: 8,
    name: "Chicken & Brown Rice Stew",
    about: "Wet food with chicken and rice.",
    description: "Delicious wet food with tender chicken and wholesome rice.",
    ingredients: ["Chicken", "Brown Rice", "Vegetables", "Vitamins"],
    price: 18.99,
    quantity: ["12 cans (3.5 oz each)", "24 cans (3.5 oz each)"],
    img: "https://m.media-amazon.com/images/I/718HoxLmQTL._AC_UL640_FMwebp_QL65_.jpg",
    category: "Wet Food",
    brand: "Annamaet",
  },
  {
    id: 9,
    name: "Organic Chicken & Quinoa",
    about: "Organic food with chicken and quinoa.",
    description: "A premium blend of organic chicken and quinoa for optimal health.",
    ingredients: ["Organic Chicken", "Quinoa", "Sweet Potatoes", "Spinach"],
    price: 32.99,
    quantity: ["5 lb", "10 lb"],
    img: "https://m.media-amazon.com/images/I/61ePMgx0n4L._AC_UL640_FMwebp_QL65_.jpg",
    category: "Dry Food",
    brand: "ACANA",
  },
  {
    id: 10,
    name: "Weight Management Blend",
    about: "Low-calorie food for weight control.",
    description: "Low-calorie blend to help pets maintain a healthy weight.",
    ingredients: ["Chicken", "Barley", "Peas", "Vitamins", "Minerals"],
    price: 29.99,
    quantity: ["6 lb", "12 lb"],
    img: "https://image.chewy.com/is/image/catalog/259516_MAIN._AC_SS348_V1712635267_.jpg",
    category: "Veterinary Diets",
    brand: "Chewy",
  },
  {
    id: 11,
    name: "Hairball Control Formula",
    about: "Food to help control hairballs.",
    description: "Specially formulated to reduce hairballs in cats.",
    ingredients: ["Chicken", "Rice", "Fiber", "Omega-3"],
    price: 26.99,
    quantity: ["5 lb", "10 lb"],
    img: "https://image.chewy.com/is/image/catalog/259516_MAIN._AC_SS348_V1712635267_.jpg",
    category: "Shop by Health Condition",
    brand: "Artemis",
  },
  
];
